In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [4]:
dataset = sns.load_dataset("iris")
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# logistical forecast (classification)

In [10]:
# Assuming dataset is your DataFrame containing both features and target variable
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

dataset.iloc[:, :-1]: Here the Pandas function is being used iloc to access the data in dataset. iloc allows indexing by integers, so iloc[:, :-1]selects all rows ( :) and all columns except the last one ( :-1). In other words, this selects all columns of the DataFrame except the last column, which is usually done to separate the features (independent variables) from the target variable (dependent variable).

dataset.iloc[:, -1]: Similar to the previous one, iloc[:, -1]selects all rows ( :) but only the last column ( -1). This selects only the last column of the DataFrame, which is normally considered the target variable (dependent variable).

In summary, these two lines of code divide the DataFrame dataset into two parts:

xcontains all features (independent variables) of the dataset as it excludes the last column.
ycontains the target variable (dependent variable), as it only includes the last column.
This is a common data preparation for training machine learning models, where x will be used to train the model and y will be the target that the model will try to fit to.

In [11]:
# Split the dataset into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [12]:
# Create and train the logistic regression model
model = LogisticRegression()
model.fit(x_train, y_train)

C:\Users\dsant\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [13]:
predict = model.predict(x_test)

In [14]:
x_test["prediction"] = predict

y_test = pd.DataFrame(y_test)

x_test["real"] = y_test["species"]
x_test.head(20)

,sepal_length,sepal_width,petal_length,petal_width,prediction,real
79,5.7,2.6,3.5,1.0,versicolor,versicolor
116,6.5,3.0,5.5,1.8,virginica,virginica
42,4.4,3.2,1.3,0.2,setosa,setosa
33,5.5,4.2,1.4,0.2,setosa,setosa
56,6.3,3.3,4.7,1.6,versicolor,versicolor
104,6.5,3.0,5.8,2.2,virginica,virginica
115,6.4,3.2,5.3,2.3,virginica,virginica
82,5.8,2.7,3.9,1.2,versicolor,versicolor
110,6.5,3.2,5.1,2.0,virginica,virginica
52,6.9,3.1,4.9,1.5,versicolor,versicolor
138,6.0,3.0,4.8,1.8,virginica,virginica
61,5.9,3.0,4.2,1.5,versicolor,versicolor
76,6.8,2.8,4.8,1.4,versicolor,versicolor
95,5.7,3.0,4.2,1.2,versicolor,versicolor
35,5.0,3.2,1.2,0.2,setosa,setosa
81,5.5,2.4,3.7,1.0,versicolor,versicolor
13,4.3,3.0,1.1,0.1,setosa,setosa
97,6.2,2.9,4.3,1.3,versicolor,versicolor
43,5.0,3.5,1.6,0.6,setosa,setosa
1,4.9,3.0,1.4,0.2,setosa,setosa

# Golf Dataset - Classification

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [19]:
golf = pd.read_excel("golf.xlsx")
golf.head()

      clima  temp umidade vento jogar
0     sunny   hot    high    no    no
1     sunny   hot    high   yes    no
2  overcast   hot    high    no   yes
3     rainy  mild    high    no   yes
4     rainy  cool  normal    no   yes

In [21]:
le = LabelEncoder()

le.fit(golf.clima)
golf.clima = le.transform(golf.clima)

le.fit(golf.temp)
golf.temp = le.transform(golf.temp)

le.fit(golf.umidade)
golf.umidade = le.transform(golf.umidade)

le.fit(golf.vento)
golf.vento = le.transform(golf.vento)

In [22]:
golf.head()

   clima  temp  umidade  vento jogar
0      2     1        0      0    no
1      2     1        0      1    no
2      0     1        0      0   yes
3      1     2        0      0   yes
4      1     0        1      0   yes