# TUNNING - Evaluation metrics - Classification

accuracy, balanced accuracy
recall
precision
f1-Score
specificity
area under ROC

In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

C:\Users\dsant\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\dsant\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\dsant\AppData\Local\Temp\ipykernel_17112\1246032827.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_excel('churn_data.xlsx')
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer,42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors='coerce')

In [4]:
df.dtypes

customerID           object
tenure                int64
PhoneService         object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [5]:
# are there any null? 
df.isnull().any()

customerID          False
tenure              False
PhoneService        False
Contract            False
PaperlessBilling    False
PaymentMethod       False
MonthlyCharges      False
TotalCharges         True
Churn               False
dtype: bool

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7042 entries, 0 to 7041
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7042 non-null   object
 1   tenure            7042 non-null   int64
 2   PhoneService      7042 non-null   object
 3   Contract          7042 non-null   object
 4   PaperlessBilling  7042 non-null   object
 5   PaymentMethod     7042 non-null   object
 6   MonthlyCharges    7042 non-null   float64
 7   TotalCharges      7031 non-null   float64
 8   Churn             7042 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 495.3+ KB

In [7]:
#Drop nulls

df= df.dropna()

# Train-Test Split

In [8]:
cat_vars = ['PhoneService',"Contract","PaperlessBilling","PaymentMethod"]
num_vars = ["tenure","MonthlyCharges","TotalCharges"]
modeling_vars = cat_vars + num_vars

In [9]:
X = df.filter(modeling_vars).copy()
y = df['Churn'].copy()
y = pd.DataFrame(y) # better to manipulate

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y.Churn) 
y.Churn = le.transform(y.Churn)

In [11]:
X = pd.get_dummies(X)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

# Feature Engineering -  Decision Tree

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

arvore = DecisionTreeClassifier()

parameters = {
    "max_depth":[1,2,3,4,5,6,7,8,9,10]
}

grid_search = GridSearchCV(arvore, parameters, scoring="roc_auc", cv=5, n_jobs=-1)

In [17]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='roc_auc')

In [18]:
results = pd.DataFrame(grid_search.cv_results_)

In [19]:
# Classified by rank_test_score
results.sort_values(by="rank_test_score")

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
4,0.022576,0.003487,0.010072,0.001511,5,{'max_depth': 5},0.840651,0.813122,0.813733,0.808806,0.821587,0.819580,0.011314,1
3,0.020907,0.002974,0.008369,0.000769,4,{'max_depth': 4},0.837066,0.817623,0.812021,0.808848,0.817247,0.818561,0.009820,2
5,0.028562,0.004184,0.009464,0.002396,6,{'max_depth': 6},0.833025,0.803876,0.804153,0.796754,0.821356,0.811833,0.013338,3
2,0.022810,0.005935,0.008880,0.001811,3,{'max_depth': 3},0.825146,0.808144,0.806887,0.796592,0.812306,0.809815,0.009246,4
6,0.029526,0.004055,0.010227,0.002511,7,{'max_depth': 7},0.821536,0.778341,0.792972,0.787812,0.798267,0.795786,0.014457,5
1,0.021825,0.001913,0.011228,0.001846,2,{'max_depth': 2},0.805162,0.784862,0.767826,0.765453,0.786436,0.781948,0.014415,6
7,0.031885,0.006667,0.010195,0.002089,8,{'max_depth': 8},0.804775,0.753857,0.780550,0.779586,0.784834,0.780720,0.016239,7
8,0.032894,0.003642,0.012265,0.002220,9,{'max_depth': 9},0.783317,0.743937,0.758942,0.761663,0.767096,0.762991,0.012738,8
9,0.030721,0.002310,0.009992,0.002224,10,{'max_depth': 10},0.763165,0.717252,0.732705,0.743394,0.743138,0.739931,0.015025,9
0,0.020091,0.002730,0.010507,0.001380,1,{'max_depth': 1},0.731423,0.723092,0.727647,0.725831,0.728913,0.727381,0.002812,10

# Random Forest Classifier

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Instantiate the RandomForestClassifier
rf = RandomForestClassifier()

parameters = {
    "max_depth": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "n_estimators": [100, 300, 500]
}

grid_search = GridSearchCV(rf, parameters, scoring="roc_auc", cv=5, n_jobs=-1)

grid_search.fit(X_train, y_train)

C:\Users\dsant\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'n_estimators': [100, 300, 500]},
             scoring='roc_auc')

In [34]:
# Classified by rank_test_score
results=pd.DataFrame(grid_search.cv_results_)
results.sort_values(by="rank_test_score")

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
18,0.618269,0.022819,0.039633,0.003829,7,100,"{'max_depth': 7, 'n_estimators': 100}",0.858439,0.833835,0.829778,0.823680,0.833775,0.835901,0.011862,1
19,1.700606,0.082402,0.108405,0.011418,7,300,"{'max_depth': 7, 'n_estimators': 300}",0.856604,0.834327,0.828443,0.827180,0.832825,0.835876,0.010698,2
20,2.788610,0.041112,0.160833,0.010429,7,500,"{'max_depth': 7, 'n_estimators': 500}",0.856570,0.833857,0.828688,0.825923,0.833804,0.835768,0.010838,3
17,2.580800,0.048231,0.170502,0.013764,6,500,"{'max_depth': 6, 'n_estimators': 500}",0.855912,0.833588,0.828277,0.826733,0.832437,0.835389,0.010570,4
16,1.622935,0.057432,0.096805,0.005809,6,300,"{'max_depth': 6, 'n_estimators': 300}",0.854491,0.833385,0.828678,0.828636,0.831491,0.835336,0.009744,5
23,2.866254,0.077119,0.171056,0.008418,8,500,"{'max_depth': 8, 'n_estimators': 500}",0.857560,0.833187,0.826409,0.823983,0.834231,0.835074,0.011899,6
15,0.569367,0.043498,0.045627,0.002272,6,100,"{'max_depth': 6, 'n_estimators': 100}",0.854904,0.832401,0.826828,0.827913,0.831276,0.834664,0.010327,7
14,2.418362,0.052407,0.144423,0.011161,5,500,"{'max_depth': 5, 'n_estimators': 500}",0.853029,0.831747,0.828614,0.828340,0.830966,0.834539,0.009338,8
22,1.760369,0.063550,0.115580,0.015019,8,300,"{'max_depth': 8, 'n_estimators': 300}",0.855679,0.833487,0.824836,0.823992,0.834128,0.834424,0.011433,9
13,1.458147,0.037822,0.092480,0.008549,5,300,"{'max_depth': 5, 'n_estimators': 300}",0.852213,0.832158,0.829077,0.827409,0.830287,0.834229,0.009125,10
21,0.618205,0.056604,0.044741,0.004634,8,100,"{'max_depth': 8, 'n_estimators': 100}",0.856951,0.830938,0.823243,0.821908,0.833680,0.833344,0.012617,11
12,0.509653,0.025055,0.034915,0.001762,5,100,"{'max_depth': 5, 'n_estimators': 100}",0.849521,0.832183,0.828279,0.828346,0.827267,0.833119,0.008371,12
26,2.962138,0.064389,0.161216,0.015342,9,500,"{'max_depth': 9, 'n_estimators': 500}",0.856714,0.830903,0.821412,0.818254,0.833400,0.832137,0.013527,13
10,1.390703,0.028373,0.085307,0.004491,4,300,"{'max_depth': 4, 'n_estimators': 300}",0.848731,0.829399,0.828269,0.826755,0.827394,0.832110,0.008358,14
11,2.293106,0.072432,0.135541,0.006153,4,500,"{'max_depth': 4, 'n_estimators': 500}",0.848063,0.828842,0.827678,0.826119,0.827273,0.831595,0.008280,15
25,1.807646,0.069243,0.124327,0.011156,9,300,"{'max_depth': 9, 'n_estimators': 300}",0.856912,0.829620,0.820809,0.817481,0.832808,0.831526,0.013870,16
24,0.598723,0.030489,0.040678,0.001629,9,100,"{'max_depth': 9, 'n_estimators': 100}",0.855993,0.827178,0.821621,0.818635,0.832598,0.831205,0.013285,17
9,0.488910,0.021084,0.039761,0.006792,4,100,"{'max_depth': 4, 'n_estimators': 100}",0.844668,0.829476,0.829012,0.828160,0.823296,0.830922,0.007218,18
8,2.143837,0.061697,0.133881,0.010217,3,500,"{'max_depth': 3, 'n_estimators': 500}",0.842514,0.824411,0.827478,0.826814,0.822337,0.828711,0.007138,19
6,0.461224,0.022945,0.033910,0.005885,3,100,"{'max_depth': 3, 'n_estimators': 100}",0.837023,0.825880,0.826119,0.824565,0.826069,0.827931,0.004582,20
29,2.345807,0.065525,0.093442,0.005561,10,500,"{'max_depth': 10, 'n_estimators': 500}",0.854292,0.826028,0.817078,0.812415,0.829517,0.827866,0.014557,21
7,1.290334,0.041124,0.091583,0.011604,3,300,"{'max_depth': 3, 'n_estimators': 300}",0.839578,0.824935,0.827820,0.825293,0.820580,0.827641,0.006407,22
28,1.803476,0.023109,0.087897,0.008283,10,300,"{'max_depth': 10, 'n_estimators': 300}",0.853001,0.827045,0.816068,0.812322,0.828580,0.827403,0.014231,23
27,0.642830,0.043591,0.050585,0.007030,10,100,"{'max_depth': 10, 'n_estimators': 100}",0.848853,0.826534,0.813608,0.813707,0.829766,0.826494,0.012963,24
5,1.958405,0.079435,0.136045,0.027227,2,500,"{'max_depth': 2, 'n_estimators': 500}",0.834555,0.818896,0.825769,0.824405,0.817474,0.824220,0.006052,25
3,0.477264,0.074087,0.032965,0.002991,2,100,"{'max_depth': 2, 'n_estimators': 100}",0.833788,0.818309,0.830395,0.821560,0.815334,0.823877,0.007072,26
4,1.199674,0.129193,0.078986,0.004446,2,300,"{'max_depth': 2, 'n_estimators': 300}",0.833731,0.818110,0.826304,0.822463,0.812602,0.822642,0.007180,27
0,0.446222,0.015064,0.032669,0.003495,1,100,"{'max_depth': 1, 'n_estimators': 100}",0.823506,0.802765,0.824194,0.810514,0.807129,0.813622,0.008708,28
1,1.145000,0.067668,0.077157,0.019674,1,300,"{'max_depth': 1, 'n_estimators': 300}",0.814418,0.801428,0.820538,0.818938,0.804536,0.811972,0.007673,29
2,1.910483,0.107551,0.110935,0.004924,1,500,"{'max_depth': 1, 'n_estimators': 500}",0.812675,0.800481,0.824882,0.814732,0.805345,0.811623,0.008368,30

In [35]:
grid_search.best_estimator_.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 7,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# Randomizer Search

In [ ]:
!pip uninstall dask lightgbm

In [ ]:
!pip install dask lightgbm

In [48]:
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier()

KeyError: 'query-planning'